name       : kidentitymanagement
version    : 18.12.3
release    : 20
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.3/src/kidentitymanagement-18.12.3.tar.xz : 4e8cac86c2ecfe6325bbf8fb7e50a026f6af978be3809f327eddfed7b3aed662
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
