name       : kidentitymanagement
version    : 18.04.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/kidentitymanagement-18.04.0.tar.xz : dc33a5197ca3a712fa86e70f4b0361e0744bb9f2310791bea8efdf29151a2a89
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Manage PIM identity.
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
