name       : kidentitymanagement
version    : 17.12.2
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/kidentitymanagement-17.12.2.tar.xz : eb8e83dded4fe0b67c7c13de398925a985787d1510e95426e2bced73d793bde8
license    : LGPL-2.1
component  : desktop.library
summary    : Manage PIM identity.
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - ktextwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
