name       : kidentitymanagement
version    : 19.12.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/kidentitymanagement-19.12.0.tar.xz : bff240fea3f22d6137c7eabbc4161401f6c67a6501c16233812482cdd204442a
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
