name       : kidentitymanagement
version    : 20.08.2
release    : 41
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.2/src/kidentitymanagement-20.08.2.tar.xz : 17a1fd47d91289519cafb12c0d917b4775496ada447cb6f4ba56dc42446152ec
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
