name       : kidentitymanagement
version    : 18.12.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/kidentitymanagement-18.12.0.tar.xz : d3cb3d2bcb96346569057f2fc21d459fff77b86f5c6caed407806d51d3aa0ac4
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
