name       : kidentitymanagement
version    : 20.04.3
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.3/src/kidentitymanagement-20.04.3.tar.xz : 09e63cdb07bb38ba8c82d796212b1bd9d218dbe8adde215bff9c689c93b90917
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
