name       : kidentitymanagement
version    : 20.08.3
release    : 42
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/kidentitymanagement-20.08.3.tar.xz : 9aae7d4a924bbaa4a927821eb65bcf2c30204d6d3fd4f432a678704fdc6e7e6e
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
