name       : kidentitymanagement
version    : 18.08.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/kidentitymanagement-18.08.0.tar.xz : 05ad7626bc09740e9baf3c0dccac1ddae9a1386dd23400c1ae1b7c40e3ea2de7
license    : LGPL-2.1
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
