name       : kidentitymanagement
version    : 18.04.1
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/kidentitymanagement-18.04.1.tar.xz : 38697be57352212bac54403c02fab5ea3880e75a4bd1ec682172ab9307dd61d1
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Manage PIM identity.
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
