name       : kidentitymanagement
version    : 18.08.1
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/kidentitymanagement-18.08.1.tar.xz : 9fc7e3a1a65a4e9eed4210ab445a1bf9c83300fe38b53d6831cb092c99ab3470
license    : LGPL-2.1
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
