name       : kidentitymanagement
version    : 17.04.0
release    : 1
source     :
    - https://download.kde.org/stable/applications/17.04.0/src/kidentitymanagement-17.04.0.tar.xz : dcf1a929d71344f88cb6bac86cdee0d916eddd89604b8c0384e8fd00199035ef
license    : LGPL-2.1
component  : desktop.library
summary    : Manage PIM identity.
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - ktextwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
