name       : kidentitymanagement
version    : 21.04.1
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/kidentitymanagement-21.04.1.tar.xz : d78abe162b52fea7571e49af5281ca354be82697ae2a93b923b34531d1943d4e
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
rundeps    :
    - devel :
        - kpimtextedit-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
