name       : kidentitymanagement
version    : 19.12.1
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/kidentitymanagement-19.12.1.tar.xz : 7df38592610e0ed74c55baf6670331d07b2df0c98484d5f8cf8f135b6d229702
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
