name       : kidentitymanagement
version    : 23.04.2
release    : 67
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/kidentitymanagement-23.04.2.tar.xz : 526b286c976d1d9296cfe42d26c0619a03bf179288b1e5d1fd769d4ffce630d7
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
rundeps    :
    - devel :
        - kpimtextedit-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
