name       : kidentitymanagement
version    : 22.04.0
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/kidentitymanagement-22.04.0.tar.xz : e094329de48e61b11310211833f62d8e856c2fe9cdf28b1e25e3164545c085f7
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
rundeps    :
    - devel :
        - kpimtextedit-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
