name       : kidentitymanagement
version    : 19.12.2
release    : 32
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.2/src/kidentitymanagement-19.12.2.tar.xz : b9319c0e600ec1273ab8308275651306325e9699512e78c6b99c89587d299307
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
