name       : kidentitymanagement
version    : 19.04.2
release    : 23
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.2/src/kidentitymanagement-19.04.2.tar.xz : c148d21adf85210a769b81862d41587b5b7321512b1fe5ec76a916806792851c
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
