name       : kidentitymanagement
version    : 17.12.3
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/kidentitymanagement-17.12.3.tar.xz : 7ea4ba12299ec8f97392d478ddb9f9589c4e70cecad7f0876ab3a98726cac457
license    : LGPL-2.1
component  : desktop.library
summary    : Manage PIM identity.
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - ktextwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
