name       : kidentitymanagement
version    : 17.08.1
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/kidentitymanagement-17.08.1.tar.xz : 9bef6619dd1577368b53062bb61097ffd00685e2ec1512c89dcc6d5bb69af7c6
license    : LGPL-2.1
component  : desktop.library
summary    : Manage PIM identity.
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - ktextwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
