name       : kidentitymanagement
version    : 21.08.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/kidentitymanagement-21.08.0.tar.xz : 8e7513e4fc8e6581208cd67ce43ddcd88a542747c9446f23b6be31d6c64916cb
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
rundeps    :
    - devel :
        - kpimtextedit-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
