name       : kidentitymanagement
version    : 17.08.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/kidentitymanagement-17.08.3.tar.xz : 7b20d5bf235787bf7c8d35c5ff29b60706698465137e602f8d6466d8f836224d
license    : LGPL-2.1
component  : desktop.library
summary    : Manage PIM identity.
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - ktextwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
