name       : kidentitymanagement
version    : 20.12.1
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/kidentitymanagement-20.12.1.tar.xz : c9d3a6aa4bef1b3864e7c5dd8def3f323c086321d9cedd142c131fcf574714b9
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
rundeps    :
    - devel :
        - kpimtextedit-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
