name       : kidentitymanagement
version    : 20.12.2
release    : 46
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kidentitymanagement-20.12.2.tar.xz : f2693527a0f95c39e0afa075efb7a31533014140467c393ef7a0db18337397ed
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
rundeps    :
    - devel :
        - kpimtextedit-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
