name       : kidentitymanagement
version    : 21.08.3
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/kidentitymanagement-21.08.3.tar.xz : 8b519b6ba948735d07b2922e76d430817f0dd5a499cad03cee60577998e0d001
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
rundeps    :
    - devel :
        - kpimtextedit-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
