name       : kidentitymanagement
version    : 18.08.3
release    : 16
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/kidentitymanagement-18.08.3.tar.xz : bf6a3516cfef03b182fa9cbdc10f6033bd0085e24bce1e1f78ee7d8f219e7503
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
