name       : kidentitymanagement
version    : 21.08.1
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/kidentitymanagement-21.08.1.tar.xz : e6ac20e931b894daa6506b65ad65151f07e9a32bdc808569a7327dc0c7f81376
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
rundeps    :
    - devel :
        - kpimtextedit-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
