name       : kidentitymanagement
version    : 22.08.3
release    : 63
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kidentitymanagement-22.08.3.tar.xz : 5e3f9c7bd852ca7702063aedbb85eb55954333886505e9cea337eeb441fd0bd9
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
rundeps    :
    - devel :
        - kpimtextedit-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
