name       : kidentitymanagement
version    : 18.12.2
release    : 19
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/kidentitymanagement-18.12.2.tar.xz : 1bfd4166a029332a6be1f711c94a1daa821ca1c0888e3d6dd1cec4603734af8f
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Manage PIM identity
description: |
    Manage PIM identity.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kemoticons-devel
    - kiconthemes-devel
    - kio-devel
    - kpimtextedit-devel
    - ktexteditor-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
